// Evidence Base — All Phase 2 research records
// Evidence class: FACT | QUANTITATIVE SIGNAL | USER-REPORTED EVIDENCE | INFERENCE | OBSERVATION

export type EvidenceClass =
  | "FACT"
  | "QUANTITATIVE SIGNAL"
  | "USER-REPORTED EVIDENCE"
  | "INFERENCE"
  | "OBSERVATION"
  | "HYPOTHESIS";

export type ThemeCode =
  | "SALE" | "PRICE" | "FIT" | "SIZE" | "QUALITY" | "ALT"
  | "OCCASION" | "INTENT" | "FORGET" | "OVERLOAD" | "INFO"
  | "AVAIL" | "TRUST" | "SOCIAL" | "OTHER";

export type BehavioralCode =
  | "WISH_CREATE" | "WISH_REVISIT" | "PURCHASE_CONSIDER" | "PURCHASE_DELAY"
  | "ADD_BAG" | "PURCHASE" | "ABANDON" | "ALT_PURCHASE"
  | "RETURN_EXCHANGE" | "WORKAROUND";

export interface EvidenceRecord {
  id: string;
  source: string;
  sourceTier: 1 | 2 | 3 | 4 | 5;
  date: string;
  geography: string;
  methodology: string;
  sampleSize: string | null;
  originalText: string;
  themes: ThemeCode[];
  behavioralClassification: BehavioralCode;
  wishlistRelevance: "direct" | "indirect" | "inferred";
  purchaseDelayRelevance: "high" | "medium" | "low";
  sentiment: "positive" | "negative" | "neutral";
  evidenceClass: EvidenceClass;
  hypothesesSupported: string[];
  hypothesesContradicted: string[];
  notes: string;
}

export const evidenceBase: EvidenceRecord[] = [
  {
    id: "EV-001",
    source: "Kukar-Kinney & Close — Journal of Business Research",
    sourceTier: 1,
    date: "2010+",
    geography: "Global/US",
    methodology: "Quantitative survey of online shoppers",
    sampleSize: "Large sample",
    originalText: "Wishlists and shopping carts partition decision-making. Many 'abandoners' are intentionally postponing purchase due to budget constraints or information needs — not rejecting the product.",
    themes: ["INTENT", "PRICE", "INFO"],
    behavioralClassification: "PURCHASE_DELAY",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "neutral",
    evidenceClass: "INFERENCE",
    hypothesesSupported: ["H7", "H2", "H11"],
    hypothesesContradicted: [],
    notes: "Foundational: wishlist saves are postponement, not abandonment.",
  },
  {
    id: "EV-002",
    source: "Consumer Psychology Literature — ResearchGate",
    sourceTier: 1,
    date: "2020-2023",
    geography: "Global",
    methodology: "Structural Equation Modeling & behavioral analysis",
    sampleSize: "Multiple studies",
    originalText: "Saving an item creates an 'open task' (Zeigarnik Effect) and 'virtual ownership' (Endowment Effect) — both antecedents to eventual purchase if nurtured with triggers.",
    themes: ["INTENT"],
    behavioralClassification: "PURCHASE_DELAY",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "neutral",
    evidenceClass: "INFERENCE",
    hypothesesSupported: ["H7", "H8"],
    hypothesesContradicted: [],
    notes: "Endowment Effect + Zeigarnik: open task creates recall pull that fades without reinforcement.",
  },
  {
    id: "EV-003",
    source: "GrowthSuite / UX Research Literature",
    sourceTier: 1,
    date: "2023",
    geography: "Global",
    methodology: "User behavioral tracking / A/B testing",
    sampleSize: "Multiple studies",
    originalText: "'Save for later' provides psychological safety, reducing the cognitive load of infinite choices and decision overload in online retail.",
    themes: ["OVERLOAD"],
    behavioralClassification: "WISH_CREATE",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "medium",
    sentiment: "neutral",
    evidenceClass: "FACT",
    hypothesesSupported: ["H10", "H8"],
    hypothesesContradicted: [],
    notes: "Wishlist reduces decision fatigue at browse time but defers the conversion problem.",
  },
  {
    id: "EV-004",
    source: "Cialdini et al. — Social Influence Literature",
    sourceTier: 1,
    date: "Classic / updated 2020s",
    geography: "Global",
    methodology: "Experimental RCTs",
    sampleSize: "Multiple RCTs",
    originalText: "Scarcity and urgency signals (low stock warnings, time-limited offers) reliably increase purchase probability by triggering loss aversion.",
    themes: ["AVAIL", "INTENT"],
    behavioralClassification: "PURCHASE_CONSIDER",
    wishlistRelevance: "indirect",
    purchaseDelayRelevance: "high",
    sentiment: "neutral",
    evidenceClass: "FACT",
    hypothesesSupported: ["H9", "H7"],
    hypothesesContradicted: [],
    notes: "Behavioral economics support for urgency-based wishlist nudges.",
  },
  {
    id: "EV-005",
    source: "Behavioral Economics — Present Bias Literature",
    sourceTier: 1,
    date: "Academic consensus",
    geography: "Global",
    methodology: "Multiple methodologies",
    sampleSize: "Multiple studies",
    originalText: "Present bias: users consistently prefer immediate gratification. 'I'll buy later' creates systematic friction in completing deferred purchase intentions.",
    themes: ["INTENT"],
    behavioralClassification: "PURCHASE_DELAY",
    wishlistRelevance: "indirect",
    purchaseDelayRelevance: "high",
    sentiment: "neutral",
    evidenceClass: "FACT",
    hypothesesSupported: ["H7", "H6"],
    hypothesesContradicted: [],
    notes: "Explains why even high-intent wishlist saves fail to convert without external triggers.",
  },
  {
    id: "EV-006",
    source: "Bain & Company — Indian E-retail Market Report",
    sourceTier: 2,
    date: "2023/24",
    geography: "India",
    methodology: "Market research",
    sampleSize: "Industry-level",
    originalText: "Indian e-retail market to reach $170–190B by 2030, heavily driven by value-led shoppers and Gen-Z segments who are highly price-sensitive.",
    themes: ["PRICE"],
    behavioralClassification: "PURCHASE_DELAY",
    wishlistRelevance: "indirect",
    purchaseDelayRelevance: "medium",
    sentiment: "neutral",
    evidenceClass: "FACT",
    hypothesesSupported: ["H2", "H1"],
    hypothesesContradicted: [],
    notes: "Value-led orientation supports price sensitivity as major conversion barrier in India.",
  },
  {
    id: "EV-007",
    source: "Redseer/BCG — E-Commerce Benchmarks India",
    sourceTier: 2,
    date: "2023",
    geography: "India",
    methodology: "Platform analytics / industry survey",
    sampleSize: "Industry aggregate",
    originalText: "Cart abandonment rate: 60–70% of all checkout initiations. Mobile fashion shopping accounts for 80–85% of transactions.",
    themes: ["PRICE", "OTHER"],
    behavioralClassification: "ABANDON",
    wishlistRelevance: "indirect",
    purchaseDelayRelevance: "medium",
    sentiment: "neutral",
    evidenceClass: "QUANTITATIVE SIGNAL",
    hypothesesSupported: ["H2", "H1"],
    hypothesesContradicted: [],
    notes: "DENOMINATOR: % of checkout initiations, NOT wishlist additions. Do NOT conflate with wishlist conversion.",
  },
  {
    id: "EV-008",
    source: "McKinsey / Consumer Insights",
    sourceTier: 1,
    date: "2022-2024",
    geography: "India/Global",
    methodology: "Consumer survey + funnel analysis",
    sampleSize: "Large sample",
    originalText: "50–60% of items left in shopping carts are treated as wishlists or comparison tools — representing intentional postponement rather than abandonment.",
    themes: ["INTENT", "ALT"],
    behavioralClassification: "PURCHASE_DELAY",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "neutral",
    evidenceClass: "QUANTITATIVE SIGNAL",
    hypothesesSupported: ["H7", "H5", "H8"],
    hypothesesContradicted: [],
    notes: "DENOMINATOR: % of abandoned carts. Methodology unverified for India-specific split. Directional use only.",
  },
  {
    id: "EV-009",
    source: "ASOS Platform / The Industry Fashion Analysis",
    sourceTier: 3,
    date: "2023",
    geography: "Global",
    methodology: "Platform feature analysis",
    sampleSize: null,
    originalText: "ASOS Saved Items (Boards): groups items into visual themes with price/stock alerts and 60-day auto-expiry. Increases time-in-app; social sharing drives top-of-funnel.",
    themes: ["INFO", "SOCIAL", "AVAIL"],
    behavioralClassification: "WISH_REVISIT",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "positive",
    evidenceClass: "OBSERVATION",
    hypothesesSupported: ["H11", "H12"],
    hypothesesContradicted: [],
    notes: "Competitor benchmark: addresses information gap (price alerts) + social + urgency (60-day expiry).",
  },
  {
    id: "EV-010",
    source: "Myntra Strategy Analysis — E-commerce PM Case Studies",
    sourceTier: 3,
    date: "2023-2024",
    geography: "India",
    methodology: "Product strategy analysis",
    sampleSize: null,
    originalText: "Myntra strategically primes wishlist builds 2-3 weeks before EORS (End of Reason Sale) to guarantee day-1 GMV spikes.",
    themes: ["SALE"],
    behavioralClassification: "WISH_CREATE",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "neutral",
    evidenceClass: "INFERENCE",
    hypothesesSupported: ["H1"],
    hypothesesContradicted: [],
    notes: "Confirms H1 is real and strategically cultivated. Between-sale conversion is the unaddressed gap.",
  },
  {
    id: "EV-011",
    source: "Myntra Platform Analysis — Feature Inventory",
    sourceTier: 3,
    date: "2024",
    geography: "India",
    methodology: "Direct platform inspection",
    sampleSize: null,
    originalText: "Myntra has no native automated push notification for price drops on wishlisted items. Users rely on third-party tools like Flipshope browser extension.",
    themes: ["INFO", "SALE"],
    behavioralClassification: "WORKAROUND",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "negative",
    evidenceClass: "OBSERVATION",
    hypothesesSupported: ["H11", "H1"],
    hypothesesContradicted: [],
    notes: "CRITICAL: Confirmed product gap. Absence of native price-drop alert is core of H11.",
  },
  {
    id: "EV-012",
    source: "Myntra Platform Analysis — Fit Assist Feature",
    sourceTier: 3,
    date: "2024",
    geography: "India",
    methodology: "Direct platform inspection",
    sampleSize: null,
    originalText: "Myntra's Fit Assist provides AI-based size recommendations. However, it does NOT notify users in the wishlist when an OOS recommended size returns to stock.",
    themes: ["FIT", "AVAIL"],
    behavioralClassification: "WISH_REVISIT",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "negative",
    evidenceClass: "OBSERVATION",
    hypothesesSupported: ["H3", "H9"],
    hypothesesContradicted: [],
    notes: "Gap between existing Fit Assist and wishlist notification integration.",
  },
  {
    id: "EV-013",
    source: "Plotline.so — Ajio UX Analysis",
    sourceTier: 3,
    date: "2024",
    geography: "India",
    methodology: "UX analysis",
    sampleSize: null,
    originalText: "Ajio uses UX coachmarks to drive wishlist adoption and integrates cross-app sharing, creating a collaborative validation loop.",
    themes: ["SOCIAL"],
    behavioralClassification: "WISH_CREATE",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "low",
    sentiment: "positive",
    evidenceClass: "OBSERVATION",
    hypothesesSupported: ["H12"],
    hypothesesContradicted: [],
    notes: "Competitor uses social validation as wishlist adoption driver.",
  },
  {
    id: "EV-014",
    source: "Myntra PM Case Studies — Conversion Funnel",
    sourceTier: 3,
    date: "2023-2024",
    geography: "India",
    methodology: "Product analytics interpretation",
    sampleSize: null,
    originalText: "The biggest drop-off in Myntra's conversion funnel is reported at the Wishlist → Add-to-Bag step. Discount nudges and back-in-stock alerts have been identified as priorities.",
    themes: ["INFO", "AVAIL", "PRICE"],
    behavioralClassification: "PURCHASE_DELAY",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "neutral",
    evidenceClass: "QUANTITATIVE SIGNAL",
    hypothesesSupported: ["H1", "H9", "H11"],
    hypothesesContradicted: [],
    notes: "DENOMINATOR UNVERIFIED — directional signal only.",
  },
  {
    id: "EV-015",
    source: "Reddit — r/IndianFashionAddicts",
    sourceTier: 4,
    date: "2023-2024",
    geography: "India",
    methodology: "Organic forum discussion",
    sampleSize: null,
    originalText: "waiting for a Myntra sale [before buying wishlisted items]",
    themes: ["SALE", "PRICE"],
    behavioralClassification: "PURCHASE_DELAY",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "neutral",
    evidenceClass: "USER-REPORTED EVIDENCE",
    hypothesesSupported: ["H1", "H2"],
    hypothesesContradicted: [],
    notes: "Direct user statement of sale-waiting behavior.",
  },
  {
    id: "EV-016",
    source: "Reddit — r/india",
    sourceTier: 4,
    date: "2023-2024",
    geography: "India",
    methodology: "Organic forum discussion",
    sampleSize: null,
    originalText: "suspicious price hikes after adding items to... wishlist [on Myntra]",
    themes: ["TRUST", "PRICE"],
    behavioralClassification: "ABANDON",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "negative",
    evidenceClass: "USER-REPORTED EVIDENCE",
    hypothesesSupported: ["H13"],
    hypothesesContradicted: [],
    notes: "H13 trigger: users perceive wishlisting triggers price increase.",
  },
  {
    id: "EV-017",
    source: "Reddit — r/IndianBeautyDeals",
    sourceTier: 4,
    date: "2023-2024",
    geography: "India",
    methodology: "Organic forum discussion",
    sampleSize: null,
    originalText: "Run to Myntra [when items restock — community serving as restock alert]",
    themes: ["AVAIL"],
    behavioralClassification: "WORKAROUND",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "neutral",
    evidenceClass: "USER-REPORTED EVIDENCE",
    hypothesesSupported: ["H9"],
    hypothesesContradicted: [],
    notes: "Reddit community used as restock alert because Myntra's notification is unreliable.",
  },
  {
    id: "EV-018",
    source: "Reddit — r/IndianFashionAddicts",
    sourceTier: 4,
    date: "2023-2024",
    geography: "India",
    methodology: "Organic forum discussion",
    sampleSize: null,
    originalText: "clearing out their entire wishlists [to reduce] FOMO [rather than purchasing]",
    themes: ["OVERLOAD", "INTENT"],
    behavioralClassification: "ABANDON",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "negative",
    evidenceClass: "USER-REPORTED EVIDENCE",
    hypothesesSupported: ["H10", "H7"],
    hypothesesContradicted: [],
    notes: "Decision overload leads to mass deletion, not conversion.",
  },
  {
    id: "EV-019",
    source: "Reddit — r/IndianFashionAddicts",
    sourceTier: 4,
    date: "2024",
    geography: "India",
    methodology: "Organic forum discussion",
    sampleSize: null,
    originalText: "App glitches where 'sold out' items will not disappear [from wishlist]",
    themes: ["AVAIL", "OTHER"],
    behavioralClassification: "WISH_REVISIT",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "medium",
    sentiment: "negative",
    evidenceClass: "USER-REPORTED EVIDENCE",
    hypothesesSupported: ["H9"],
    hypothesesContradicted: [],
    notes: "Dead OOS items clutter wishlist, hiding active purchase-intent items.",
  },
  {
    id: "EV-020",
    source: "App Review Aggregation — Google Play / App Store",
    sourceTier: 4,
    date: "2023-2024",
    geography: "India",
    methodology: "Aggregated review analysis",
    sampleSize: null,
    originalText: "No native push notification when wishlisted item drops in price. Users install Flipshope to track externally.",
    themes: ["INFO", "SALE"],
    behavioralClassification: "WORKAROUND",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "negative",
    evidenceClass: "USER-REPORTED EVIDENCE",
    hypothesesSupported: ["H11", "H1"],
    hypothesesContradicted: [],
    notes: "Workaround behavior (Flipshope) confirms desire for price tracking — a product gap.",
  },
  {
    id: "EV-021",
    source: "App Review Aggregation — Google Play / App Store",
    sourceTier: 4,
    date: "2023-2024",
    geography: "India",
    methodology: "Aggregated review analysis",
    sampleSize: null,
    originalText: "Instant price hikes seen immediately after an item is wishlisted [on Myntra]",
    themes: ["TRUST", "PRICE"],
    behavioralClassification: "ABANDON",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "high",
    sentiment: "negative",
    evidenceClass: "USER-REPORTED EVIDENCE",
    hypothesesSupported: ["H13"],
    hypothesesContradicted: [],
    notes: "Corroborates EV-016. Dynamic pricing perception is a potential trust barrier.",
  },
  {
    id: "EV-022",
    source: "Reddit — r/IndianFashionAddicts + fashion communities",
    sourceTier: 4,
    date: "2023-2024",
    geography: "India",
    methodology: "Organic forum discussion",
    sampleSize: null,
    originalText: "Sharing wishlists via the 'pen icon' to get feedback from friends [before buying]",
    themes: ["SOCIAL"],
    behavioralClassification: "WORKAROUND",
    wishlistRelevance: "direct",
    purchaseDelayRelevance: "medium",
    sentiment: "positive",
    evidenceClass: "USER-REPORTED EVIDENCE",
    hypothesesSupported: ["H12", "H8"],
    hypothesesContradicted: [],
    notes: "Social validation use case: wishlist as outfit sharing tool.",
  },
];

export const hypotheses = [
  { id: "H1",  name: "Sale / Price-Drop Anticipation",      definition: "Users deliberately delay purchase, waiting for a discount event (EORS, seasonal sale)" },
  { id: "H2",  name: "Current Price Too High",               definition: "Users want the item but cannot afford or justify the current price" },
  { id: "H3",  name: "Fit / Size Uncertainty",              definition: "Users are uncertain whether the product will fit them correctly based on online sizing" },
  { id: "H4",  name: "Quality / Material Uncertainty",      definition: "Users cannot verify real-world quality or material from product images/descriptions" },
  { id: "H5",  name: "Alternative Comparison",              definition: "Users are comparing with other products or platforms and have not yet decided" },
  { id: "H6",  name: "Occasion / Timing",                   definition: "Users have no current occasion or need — saving for a future event" },
  { id: "H7",  name: "Intent Decay",                        definition: "Initial interest faded naturally without reinforcement triggers" },
  { id: "H8",  name: "Wishlist as Bookmarking Tool",        definition: "Users save items with no real purchase intent — it is a discovery/inspiration mechanism" },
  { id: "H9",  name: "Availability / OOS Constraint",       definition: "Required size or color was unavailable when the user was ready to purchase" },
  { id: "H10", name: "Decision Overload",                   definition: "Too many saved items leads to decision paralysis — none get purchased" },
  { id: "H11", name: "Information Gap (No Alerts)",         definition: "User lacks price-drop alerts and restock notifications — cannot know when to return" },
  { id: "H12", name: "Social Validation Seeking",           definition: "User wants external validation from friends or reviews before committing" },
  { id: "H13", name: "Dynamic Pricing / Trust Concern",     definition: "User believes wishlisting causes price increase — disincentive to save or return" },
];

export const themeLabels: Record<ThemeCode, string> = {
  SALE: "Sale / Price-Drop Anticipation",
  PRICE: "Current Price Too High",
  FIT: "Fit Uncertainty",
  SIZE: "Size Availability",
  QUALITY: "Quality / Material Uncertainty",
  ALT: "Alternative Comparison",
  OCCASION: "Occasion / Timing",
  INTENT: "Intent Decay",
  FORGET: "Forgetting",
  OVERLOAD: "Decision Overload",
  INFO: "Information Gap",
  AVAIL: "Availability / OOS",
  TRUST: "Trust / Dynamic Pricing",
  SOCIAL: "Social Validation Seeking",
  OTHER: "Other",
};
